-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 10:53:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login` DEFAULT CHARACTER SET utf8 ;
USE `login` ;

-- -----------------------------------------------------
-- Table `login`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login`.`logins` ;

CREATE TABLE IF NOT EXISTS `login`.`logins` (
  `idlogins` INT NOT NULL,
  `loginName` VARCHAR(45) NOT NULL,
  `loginSurname` VARCHAR(45) NOT NULL,
  `loginPassw` VARCHAR(45) NOT NULL,
  `loginUsername` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlogins`),
  UNIQUE INDEX `loginUsername_UNIQUE` (`loginUsername` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
